const cors = require('cors')
const express = require('express')
const app = express()
app.use(express.json())
app.use(cors())
const dotenv = require('dotenv')
dotenv.config()
const AuthRouter = require('./src/routes/authRouter')
const CommentRouter = require('./src/routes/commentRouter')
const ProductRouter = require('./src/routes/productRouter')
const UserRouter = require('./src/routes/userRouter')
const ConnectRouter = require('./src/routes/connectRouter')
const BankingRouter = require('./src/routes/bankingRouter')
const ImageRouter = require('./src/routes/imageRouter')

app.get('/', (_, res) => {
  res.send('Hello World!')
})
app.use('/api', cors({ origin: '*' }), AuthRouter)
app.use('/api', cors({ origin: '*' }), CommentRouter)
app.use('/api', cors({ origin: '*' }), ProductRouter)
app.use('/api', cors({ origin: '*' }), UserRouter)
app.use('/api', cors({ origin: '*' }), ConnectRouter)
app.use('/api', cors({ origin: '*' }), BankingRouter)
app.use('/api', cors({ origin: '*' }), ImageRouter)
app.listen(5000, () => {
  console.log('Server is running on port 5000.')
})
